### ISSUE TITLE
Supporting FROM name/version

### ISSUE THREAD

**Issue by prologic** [mickep76/docker-build-ami#1]
Just looking at your [TODO](https://raw.githubusercontent.com/mickep76/docker-build-ami/master/TODO.md) and noticed:

> - Support source image using name/version

How do we plan to support this? (_I wasn't even aware you could reference AWS AMI(s) by name/version?_)

**Comment by ake-persson** [comment]
You can't since they are Tags, but you can lookup the tags and trace them
to which AMI they represent.

**Comment by prologic** [comment]
So what did you have in mind for this TODO item?

**Comment by ake-persson** [comment]
The use case for me is when you have a base image that is basically an AMI
that you built from a prev. Dockerfile, being able to reference it using a
FROM statement inside the Dockerfile.

The main reason for this script was using the same tooling for building
Docker images as well as Machine images, it makes it easier for Developers
since they only need to learn one set of tools. Likewise we also build
physical Bare Metal images using Dockerfile so we basically have one
abstraction but with multiple targets.

**Comment by prologic** [comment]
So it would look something like:

```
FROM ami-4ead7f3

RUN ...
```

For example.

**Comment by ake-persson** [comment]
Yes indeed so the you don't need to update your Dockerfile every time you rebuild the Base image. Like:

```
FROM mycentos7:latest

RUN ...
```
